language: node_js
cache:
  directories:
    - ~/.npm
node_js:  #version de node
  - '13'
git:
  depth: 3
script:   #una ves que estos script sean resueltos bien en el servidor de travis se va a seguir con el deploy
  - yarn test
  - CI=false yarn build  
deploy:
  provider: pages  #esto es el provider que es github page. osea nuestra pagina se va alojar en el servidor de github o host. 
  edge: true
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN  #este es el token del proyecto creado en github page como en el otro nos pedia el de firebase. aca lo creamos en travis asi con este nombre y asi lo usamos oculto.
  local-dir: build/  #este es el directorio que debe mandarse a produccion el de nosotro es build
  
  commit_message: "Deploy release ${TRAVIS_TAG}"
  on:
   all_branches: true  #usando esto me fumciono el deploy