name: Build and Deploy #aca es el nombre de la action de github
on: [push] # esta es la condicion de cuando se van a hacer las siguientes dos acciones , en este caso cada ves que se haga push
   

jobs:  
  build:  #primer accion
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build #hay que sacar el prod
      - name: Archive Production Artifact
        uses: actions/upload-artifact@master
        with:
          name: dist
          path: dist
  deploy: #segunda accion
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: dist
          path: dist
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # aqui va nuestro token de firebase para tener ese token hay que hacer en  consola firebase login:ci y luego ponerlo en secrets en github esto es para que no se vea